local InventoryPrefabsList = { --每个元素的下标值为每种物品栏图片的名字
    furry_curry_omelet_rice         = 1,
    furry_fishball_scallion_noodles = 1,
    furry_jasmine_milk_tea          = 1,
    furry_wolf_milk                 = 1,
    furry_semi_cheese               = 1,
    furry_tiramisu                  = 1,
    furry_garlic_bullfrog           = 1,
    furry_butter                    = 1,
    furry_perilla_wraps             = 1,
    furry_collar_bell               = 1,
    furry_spicy_stew                = 1,
    furry_cheese_potato_bake        = 1,
    furry_marshmallow               = 1,
    furry_nut_energy_bar            = 1,
    furry_durian_mille_feuille      = 1,
    furry_nutrition_cup             = 1,
    furry_pomegranate_velvet        = 1,
    furry_banana_milk_pudding       = 1,
    furry_crispy_butterfly_pie      = 1,
    furry_creamy_clam_egg_stew      = 1,
    furry_sweet_vegetable_soup      = 1,
    furry_vanilla_cone              = 1,
    furry_turkey_feast              = 1,
    furry_herbal_tea                = 1,
    furry_french_boston_lobster     = 1,
    furry_cola_chicken_wings        = 1,
    furry_creamy_fruit_pie          = 1,
}

return InventoryPrefabsList
